from pathlib import Path
p=Path('book.html')
s=p.read_text()
old='''<h3 class="formSection">Full event address</h3><label>Street address<input name="Street address" placeholder="123 Main St" required autocomplete="street-address" id="eventAddress" inputmode="text"><div id="addressAutocompleteHost" class="addressAutocompleteHost"></div><div id="addressAutocompleteHelp" class="addressHelp">Start typing your street address.</div><input type="hidden" id="addressLat" name="Address latitude"><input type="hidden" id="addressLng" name="Address longitude"><input type="hidden" id="addressPlaceId" name="Google Place ID"></label><div class="fieldRow"><label>City<input name="Event city" placeholder="Fremont" required autocomplete="address-level2"></label><label>State<input name="Event state" placeholder="CA" required autocomplete="address-level1"></label></div><label>ZIP Code<input name="Event ZIP" placeholder="94539" required autocomplete="postal-code" inputmode="numeric" pattern="[0-9]{5}(-[0-9]{4})?"></label>'''
new='''<h3 class="formSection">Event address</h3><label>Full event address<input name="Street address" placeholder="Start typing your address" required autocomplete="street-address" id="eventAddress" inputmode="text"><div id="addressAutocompleteHost" class="addressAutocompleteHost"></div><div id="addressAutocompleteHelp" class="addressHelp">Start typing and select the complete address from the suggestions.</div><input type="hidden" id="addressLat" name="Address latitude"><input type="hidden" id="addressLng" name="Address longitude"><input type="hidden" id="addressPlaceId" name="Google Place ID"></label>'''
if old not in s: raise SystemExit('address fields not found')
s=s.replace(old,new,1)
oldsummary="function summaryStrip(){const d=formDraft['Event date']||'Not set',t=formDraft['Preferred time']||'Not set',city=formDraft['Event city']||'',state=formDraft['Event state']||'',zip=formDraft['Event ZIP']||'',z=[city,state,zip].filter(Boolean).join(', ')||'Not set';return `<div class=\"summaryStrip\"><div><small>Date</small><strong>${esc(d)}</strong></div><div><small>Time</small><strong>${esc(t)}</strong></div><div><small>Area</small><strong>${esc(z)}</strong></div></div>`}"
newsummary="function summaryStrip(){const d=formDraft['Event date']||'Not set',t=formDraft['Preferred time']||'Not set',z=formDraft['Street address']||'Not set';return `<div class=\"summaryStrip\"><div><small>Date</small><strong>${esc(d)}</strong></div><div><small>Time</small><strong>${esc(t)}</strong></div><div><small>Address</small><strong>${esc(z)}</strong></div></div>`}"
if oldsummary in s: s=s.replace(oldsummary,newsummary,1)
oldhidden="<input type=\"hidden\" name=\"Street address\" value=\"${esc(formDraft['Street address'])}\"><input type=\"hidden\" name=\"Event city\" value=\"${esc(formDraft['Event city'])}\"><input type=\"hidden\" name=\"Event state\" value=\"${esc(formDraft['Event state'])}\"><input type=\"hidden\" name=\"Event ZIP\" value=\"${esc(formDraft['Event ZIP'])}\">"
newhidden="<input type=\"hidden\" name=\"Street address\" value=\"${esc(formDraft['Street address'])}\">"
s=s.replace(oldhidden,newhidden)
oldlead="fd.append('Street address',formDraft['Street address']||'');\n fd.append('Event city',formDraft['Event city']||'');\n fd.append('Event state',formDraft['Event state']||'');\n fd.append('Event ZIP',formDraft['Event ZIP']||'');"
newlead="fd.append('Full event address',formDraft['Street address']||'');"
s=s.replace(oldlead,newlead)
p.write_text(s)
